name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker Buildx (untuk multi-architecture)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in ke DockerHub atau GitHub Container Registry (GHCR)
    - name: Log in to DockerHub or GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}  # Username GitHub yang otomatis
        password: ${{ secrets.GITHUB_TOKEN }}  # Token GitHub yang sudah ada (GitHub Actions memberikan token ini secara otomatis)

    # Build Docker Image
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/matic-api:latest

    # Push Docker Image ke GitHub Container Registry (GHCR)
    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository }}/matic-api:latest

    # Opsional: Run Docker container setelah push (untuk memastikan image berfungsi)
    - name: Run Docker container 
      run: |
        docker run --name matic-api -d ghcr.io/${{ github.repository }}/matic-api:latest
        docker ps  # Menampilkan container yang sedang berjalan
